import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/contexts/AuthContext";
import QueryProvider from "@/providers/QueryProvider";
import SidebarContent from "./admin/components/SidebarContent";
import FullScreenWrapper from "@/components/FullScreenWrapper";
import Sidebar from "./components/Sidebar";
import CartProvider from "@/contexts/CartContext";

const font = Poppins({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <QueryProvider>
              <Toaster />
              <Navbar />
              <Sidebar />
              {children}
            </QueryProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
