# Generated by Django 5.2.4 on 2025-07-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
