# Generated by Django 5.2.4 on 2025-07-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1_blog', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
