# Generated by Django 5.2.4 on 2025-07-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='kathmandu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default='9840000000'),
            preserve_default=False,
        ),
    ]
