# Generated by Django 5.2.4 on 2025-07-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1_blog', '0002_blog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
    ]
