# Generated by Django 5.2.4 on 2025-08-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='group_id',
            new_name='group',
        ),
    ]
