# Generated by Django 5.2.4 on 2025-08-13 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_rename_group_id_debt_group'),
        ('groups', '0004_alter_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debt',
            new_name='DebtModel',
        ),
    ]
