# Generated by Django 5.2.4 on 2025-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, default='/media/group_images/default.jpg', null=True, upload_to='group_images/'),
        ),
    ]
