# Generated by Django 5.2.4 on 2025-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/media/profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
