# Generated by Django 5.2.4 on 2025-07-07 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4_library', '0002_rename_loan_burrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='burrow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
