# Generated by Django 5.2.4 on 2025-07-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task3_sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
