# Generated by Django 5.2.4 on 2025-07-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5_ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
