# Generated by Django 5.2.4 on 2025-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task5_ems', '0002_alter_attendee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
